services:
  # 1. Database for Services (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: careforall_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: careforall_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis (For Idempotency & Caching)
  redis:
    image: redis:7
    container_name: careforall_redis
    ports:
      - "6379:6379"

  # 3. RabbitMQ (For Event Driven Architecture)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: careforall_broker
    ports:
      - "5672:5672"   # App connection
      - "15672:15672" # UI Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  postgres_data: